Repository Ventan00/quanda, pull requests merged in 2021-09, with the labels that each got.

#97 Bugifx/captcha randomly not rendering
  Client/Components/CaptchaComponent.razor
  Client/Components/CaptchaComponent.razor.cs
  Client/wwwroot/index.html
  Client/wwwroot/js/ReCaptcha.js
Labels: bug

#103 bugfix/missing-icons
  Client/wwwroot/css/quanda_icons/fonts/Quanda.eot
  Client/wwwroot/css/quanda_icons/fonts/Quanda.svg
  Client/wwwroot/css/quanda_icons/fonts/Quanda.ttf
  Client/wwwroot/css/quanda_icons/fonts/Quanda.woff
  Client/wwwroot/css/quanda_icons/style.css
Labels: bug

#92 Added right shared menus and configured displaying.
  .gitignore
  Client/App.razor
  Client/App.razor.cs
  Client/Components/QuestionWithAnswersComponent.razor.css
  Client/Components/QuestionsComponent.razor
  Client/Components/QuestionsComponent.razor.cs
  Client/Components/QuestionsComponent.razor.css
  Client/Pages/Home.razor
  Client/Pages/Home.razor.cs
  Client/Pages/Login.razor
  Client/Pages/Question.razor
  Client/Pages/Question.razor.cs
  Client/Pages/Recover/RecoverConfirmationEmail.razor
  Client/Pages/Recover/RecoverConfirmationEmail.razor.cs
  Client/Pages/Recover/RecoverPassword.razor
  Client/Pages/Recover/RecoverPassword.razor.cs
  Client/Pages/Recover/ResetPassword.razor
  Client/Pages/Recover/ResetPassword.razor.cs
  Client/Pages/Register.razor
  Client/Program.cs
  Client/Quanda.Client.csproj
  Client/Repositories/Implementations/UsersRepository.cs
  Client/Repositories/Interfaces/IUsersRepository.cs
  Client/Services/RightMenuStateService.cs
  Client/Shared/MainLayout.razor
  Client/Shared/MainLayout.razor.cs
  Client/Shared/MainLayout.razor.css
  Client/Shared/NavMenuComponent.razor
  Client/Shared/RightMenu/RightAskQuestion.razor
  Client/Shared/RightMenu/RightAskQuestion.razor.css
  Client/Shared/RightMenu/RightMenu.razor
  Client/Shared/RightMenu/RightMenu.razor.cs
  Client/Shared/RightMenu/RightMenu.razor.css
  Client/Shared/RightMenu/RightMenuType.cs
  Client/Shared/RightMenu/RightStandard.razor
  Client/Shared/RightMenu/RightStandard.razor.cs
  Client/Shared/RightMenu/RightStandard.razor.css
  README.md
  Server/Controllers/AccountsController.cs
  Server/Repositories/Implementations/UsersRepository.cs
  Server/Repositories/Interfaces/IUsersRepository.cs
  Shared/DTOs/Responses/Top3UserResponseDTO.cs
Labels: documentation, enhancement

#105 Feature/all tags page
  Client/Components/QuestionForAnswersComponent.razor.css
  Client/Components/QuestionWithAnswersComponent.razor
  Client/Components/QuestionWithAnswersComponent.razor.css
  Client/Components/QuestionsComponent.razor
  Client/Components/SingleTagComponent.razor
  Client/Components/SingleTagComponent.razor.css
  Client/Extensions/NavigationManagerExtension.cs
  Client/Pages/Tags/SubTags.razor
  Client/Pages/Tags/SubTags.razor.cs
  Client/Pages/Tags/SubTags.razor.css
  Client/Pages/Tags/Tags.razor
  Client/Pages/Tags/Tags.razor.cs
  Client/Pages/Tags/Tags.razor.css
  Client/Program.cs
  Client/Repositories/Implementations/AnswerRepository.cs
  Client/Repositories/Implementations/TagsRepository.cs
  Client/Repositories/Interfaces/IAnswerRepository.cs
  Client/Repositories/Interfaces/ITagsReposiotry.cs
  Client/Repositories/TagsRepository.cs
  Client/_Imports.razor
  Server/Controllers/TagsController.cs
  Server/Quanda.Server.csproj
  Server/Repositories/Implementations/TagRepository.cs
  Server/Repositories/Interfaces/ITagRepository.cs
  Server/Repositories/TagRepository.cs
  Server/Startup.cs
  Shared/Config.cs
  Shared/DTOs/Responses/SubTagsPageResponseDTO.cs
  Shared/DTOs/Responses/TagPageResponseDTO.cs
  Shared/DTOs/Responses/TagResponseDTO.cs
  Shared/Enums/SortTagsEnum.cs
Labels: enhancement
